### ISSUE TITLE
Change links to new AGORA webpage

### ISSUE THREAD

**Issue by MichaelHoffmann** [MichaelHoffmann/AGORA#295]
Since we published the new agora.gatech.edu, the links in the Flash application all lead to the AGORA frontpage. Please change the existing links as follows:

All the links below should open in a new tab in the user's browser

On Login-screen:
- "About us": http://agora.gatech.edu/node/42
- "Contact us": http://agora.gatech.edu/project/about
- "FAQ": http://agora.gatech.edu/learn/faq
- Remove "Help" button

On category screen and lists:
- "Terms of Service": http://agora.gatech.edu/learn/tos
- "About us": http://agora.gatech.edu/node/42
- "Contact us": http://agora.gatech.edu/project/about
- "FAQ": http://agora.gatech.edu/learn/faq
- Remove "Help" button

On maps:
- replace "Help" button by "Login" (see issue #294)
- "What you should know before you start": http://agora.gatech.edu/learn/what-you-should-know
- "FAQ": http://agora.gatech.edu/learn/faq

On Registration screen
- replace the link under "Click here to read them" (Terms of service) by http://agora.gatech.edu/learn/tos

**Comment by vinodhkris** [comment]
Fixed and updated.
